# Copyright (c) 2020 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.6'

services:
  ## Define Kapacitor service
  ia_kapacitor:
    depends_on:
      - ia_common
    build:
      context: $PWD/../Kapacitor/
      dockerfile: $PWD/../Kapacitor/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        KAPACITOR_VERSION: ${KAPACITOR_VERSION}
        INTELPYTHON_VERSION: ${INTELPYTHON_VERSION}
        GO_VERSION: ${GO_VERSION}
        HOST_TIME_ZONE: ${HOST_TIME_ZONE}
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
    image: ${DOCKER_REGISTRY}ia_kapacitor:${EIS_VERSION}
    container_name: ia_kapacitor
    hostname: ia_kapacitor
    network_mode: host
    read_only: true
    restart: unless-stopped
    ipc: "none"
    environment:
      AppName: "Kapacitor"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${eis_no_proxy},${ETCD_HOST}
      NO_PROXY: ${eis_no_proxy},${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      KAPACITOR_URL: http://127.0.0.1:$KAPACITOR_PORT/
      KAPACITOR_UNSAFE_SSL: "true"
      KAPACITOR_INFLUXDB_0_URLS_0: http://127.0.0.1:$INFLUXDB_PORT/
      INFLUX_SERVER: '127.0.0.1'
      KAPACITOR_SERVER: '127.0.0.1'
      KAPACITOR_PORT: $KAPACITOR_PORT
      ETCD_PREFIX: ${ETCD_PREFIX}
      CertType: "pem"
    user: ${EIS_UID}
    volumes:
       - "vol_temp_kapacitor:/tmp/"
    ports:
      - "$KAPACITOR_PORT:$KAPACITOR_PORT"
    secrets:
      - ca_etcd
      - etcd_Kapacitor_cert
      - etcd_Kapacitor_key

volumes:
  vol_temp_kapacitor:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

secrets:
  etcd_Kapacitor_cert:
    file: provision/Certificates/Kapacitor/Kapacitor_client_certificate.pem
  etcd_Kapacitor_key:
    file: provision/Certificates/Kapacitor/Kapacitor_client_key.pem
