version: '3.6'

services:
  ## Define Kapacitor service
  ia_kapacitor:
    depends_on:
      - ia_common
    build:
      context: $PWD/../Kapacitor/
      dockerfile: $PWD/../Kapacitor/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        KAPACITOR_VERSION: ${KAPACITOR_VERSION}
        INTELPYTHON_VERSION: ${INTELPYTHON_VERSION}
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
    image: ${DOCKER_REGISTRY}ia_kapacitor:${EIS_VERSION}
    container_name: ia_kapacitor
    hostname: ia_kapacitor
    network_mode: host
    read_only: true
    restart: unless-stopped
    environment:
      AppName: "Kapacitor"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${eis_no_proxy},${ETCD_HOST}
      NO_PROXY: ${eis_no_proxy},${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      KAPACITOR_URL: http://127.0.0.1:$KAPACITOR_PORT/
      KAPACITOR_UNSAFE_SSL: "true"
      KAPACITOR_INFLUXDB_0_URLS_0: http://127.0.0.1:$INFLUXDB_PORT/
      INFLUX_SERVER: '127.0.0.1'
      KAPACITOR_SERVER: '127.0.0.1'
      KAPACITOR_PORT: $KAPACITOR_PORT
      ETCD_PREFIX: ${ETCD_PREFIX}
      CertType: "pem"
    user: ${EIS_UID}
    volumes:
       - "vol_temp_kapacitor:/tmp/"
    ports:
      - "$KAPACITOR_PORT:$KAPACITOR_PORT"
    secrets:
      - ca_etcd
      - etcd_Kapacitor_cert
      - etcd_Kapacitor_key

volumes:
  vol_temp_kapacitor:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

secrets:
  etcd_Kapacitor_cert:
    file: provision/Certificates/Kapacitor/Kapacitor_client_certificate.pem
  etcd_Kapacitor_key:
    file: provision/Certificates/Kapacitor/Kapacitor_client_key.pem
