# Copyright (c) 2020 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.6'

services:
  ## Define Kapacitor service
  ia_kapacitor:
    depends_on:
      - ia_common
    build:
      context: $PWD/../Kapacitor/
      dockerfile: $PWD/../Kapacitor/Dockerfile
      args:
        EII_VERSION: ${EII_VERSION}
        KAPACITOR_VERSION: ${KAPACITOR_VERSION}
        INTELPYTHON_VERSION: ${INTELPYTHON_VERSION}
        GO_VERSION: ${GO_VERSION}
        HOST_TIME_ZONE: ${HOST_TIME_ZONE}
        CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
        EII_UID: ${EII_UID}
        EII_USER_NAME: ${EII_USER_NAME}
    image: ${DOCKER_REGISTRY}openedgeinsights/ia_kapacitor:${EII_VERSION}
    container_name: ia_kapacitor
    hostname: ia_kapacitor
    read_only: true
    restart: unless-stopped
    ipc: "none"
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m    
    environment:
      AppName: "Kapacitor"
      DEV_MODE: ${DEV_MODE}
      PROFILING_MODE: ${PROFILING_MODE}
      no_proxy: "${ETCD_HOST},ia_influxdbconnector,ia_kapacitor"
      NO_PROXY: "${ETCD_HOST},ia_influxdbconnector,ia_kapacitor"
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      KAPACITOR_URL: http://ia_kapacitor:$KAPACITOR_PORT/
      KAPACITOR_UNSAFE_SSL: "true"
      KAPACITOR_INFLUXDB_0_URLS_0: http://ia_influxdbconnector:$INFLUXDB_PORT/
      INFLUX_SERVER: 'ia_influxdbconnector'
      KAPACITOR_SERVER: 'ia_kapacitor'
      KAPACITOR_PORT: $KAPACITOR_PORT
      ETCD_PREFIX: ${ETCD_PREFIX}
      INFLUXDB_USERNAME: ${INFLUXDB_USERNAME}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
    networks:
      - eii
    volumes:
       - "vol_temp_kapacitor:/tmp/"
       - "vol_eii_socket:${SOCKET_DIR}"
       - "vol_dev_shm:/dev/shm"
       - ./Certificates/Kapacitor:/run/secrets/Kapacitor:ro
       - ./Certificates/rootca/cacert.pem:/run/secrets/rootca/cacert.pem:ro
    ports:
      - "$KAPACITOR_PORT:$KAPACITOR_PORT"

volumes:
  vol_temp_kapacitor:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

  vol_dev_shm:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

